model:
    in_channels: 1
    down_num: 5
train:
    mini_batch_size: 64
    epochs: 100
    snapshot_freq_epoch: 20
    ckp_point_path: "./checkpoints"
    decoder_ckp_for_load: 100
data:
    data_store_path: '/path/to/data'
    modalities_num: 4
    modalities_name: ['Flair.nii.gz','T1.nii.gz','T1c.nii.gz','T2.nii.gz' ]


optim:
    weight_decay: 0.00001
    lr: 0.00001


